//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobMan.Storage.SqlServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobMan.Storage.SqlServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF not EXISTS(SELECT * FROM sys.indexes WHERE object_id = object_id(&apos;jm_jobs&apos;) AND NAME =&apos;ix_jobs_Status&apos;)
        /// create index ix_jobs_Status on jm_jobs ([Status]) where [Status] = 10.
        /// </summary>
        internal static string AdditionalIndex01SQL {
            get {
                return ResourceManager.GetString("AdditionalIndex01SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM sysobjects WHERE name=&apos;jm_jobs&apos; and xtype=&apos;U&apos;)
        /// create table jm_jobs
        /// (
        ///  [Id] bigint identity(1,1) primary key,
        ///  [Schedule] uniqueidentifier, 
        ///  [Type] int not null,
        ///  [Pool] nvarchar(50) not null,
        ///  [Cron] nvarchar(40),
        ///  [Tag] nvarchar(40),
        ///
        ///  LastExecuteTime datetime,
        ///  NextExecuteTime datetime not null,
        ///
        ///  [Status] int not null,
        ///  [ProcessTimeMs] bigint,
        ///  [RetryCount] int,
        ///
        ///  Data nvarchar(max),
        ///  [Description] nvarchar(200)
        ///)
        ///
        ///GO;
        ///
        ///IF not EXISTS(SE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SchemaSQLServer {
            get {
                return ResourceManager.GetString("SchemaSQLServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF COL_LENGTH(&apos;jm_jobs&apos;,&apos;RetryCount&apos;) IS NULL
        ///BEGIN
        /// alter table jm_jobs add [RetryCount] int
        ///END.
        /// </summary>
        internal static string Update01Sql {
            get {
                return ResourceManager.GetString("Update01Sql", resourceCulture);
            }
        }
    }
}
