//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobMan.Storage.PostgreSql.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobMan.Storage.PostgreSql.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS public.jm_jobs
        /// (
        ///  Id BIGSERIAL PRIMARY KEY,
        ///  Schedule uuid, 
        ///  Type int not null,
        ///  Pool varchar(50) not null,
        ///  Cron varchar(40),
        ///  Tag varchar(40),
        ///
        ///  LastExecuteTime timestamp,
        ///  NextExecuteTime timestamp not null,
        ///
        ///  Status int not null,
        ///  ProcessTimeMs bigint,
        ///  RetryCount int,
        ///
        ///  Data text,
        ///  Description text
        ///);
        ///
        ///GO;
        ///
        ///CREATE INDEX IF NOT EXISTS ix_jobs_NextExecuteTime on jm_jobs (Status, Pool, NextExecuteTime)
        /// where ( Status = 10 )
        ///
        ///GO;
        ///
        ///CREATE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SchemaPostgreSql {
            get {
                return ResourceManager.GetString("SchemaPostgreSql", resourceCulture);
            }
        }
    }
}
